process message events and send to server
swecc-uw/swecc-bot pull request #21
Opened 2024-12-29 02:18 UTC by elimelt

2024-12-29 10:28 UTC, mjh316 requested changes

2024-12-29 10:28 UTC, mjh316 commented on APIs/SweccAPI.py
> +            response = requests.post(
Switch to aiohttp

2024-12-29 22:36 UTC, Advayp approved these changes
LGTM

2024-12-31 04:43 UTC, mjh316 approved these changes

2024-12-31 04:48 UTC, merged